Imports System
Imports System.Collections
Imports System.Text
Imports Microsoft.VisualBasic

Public Class PrioridadeDAO
    Dim ObjPrioridadeVO As PrioridadeVO
    Dim ObjPrioridadeDAO As PrioridadeDAO
    Public Function ConsultaPrioridade(ByVal ObjPrioridadeVO As PrioridadeVO, ByVal DataPesquisa As Date, ByVal Federacao As String, ByVal AliasBanco As String) As IList
        Try
            Dim Conn = New Banco.Conexao(AliasBanco)
            Dim VarSql = New Text.StringBuilder("SET NOCOUNT ON ")
            With VarSql
                .AppendLine("Declare @Dia varchar(10), @ApaId varchar(10), @Federacao char(1), @ListaCaract varchar(1000) ")
                .AppendLine("Set @Dia = '" & DataPesquisa & "' ")
                .AppendLine("Set @ApaId = '" & ObjPrioridadeVO.ApaId & "' ")
                .AppendLine("Set @Federacao = '" & Federacao & "' ")
                .AppendLine("Set @ListaCaract = '' ")
                .AppendLine("declare ")
                .AppendLine("  @ApaDesc varchar(10), ")
                .AppendLine("  @ApaStatus char(1), ")
                .AppendLine("  @Qtde smallint, ")
                .AppendLine("  @DataIni datetime, ")
                .AppendLine("  @SolId numeric, ")
                .AppendLine("  @ManDescricaoRequis varchar(200), ")
                .AppendLine("  @IntId numeric, ")
                .AppendLine("  @IntNome varchar(80), ")
                .AppendLine("  @HosDataFimSol varchar(10), ")
                .AppendLine("  @HosHoraFimSol varchar(3), ")
                .AppendLine("  @Integrante smallint, ")
                .AppendLine("  @SolBerco smallint, ")
                .AppendLine("  @CC smallint, ")
                .AppendLine("  @CS smallint, ")
                .AppendLine("  @CE smallint, ")
                .AppendLine("  @BE smallint,")
                .AppendLine("  @JT smallint, ")
                .AppendLine("  @FR smallint, ")
                .AppendLine("  @ApaCamaExtra smallint, ")
                .AppendLine("  @ApaBerco smallint, ")
                .AppendLine("  @AptoPrioridadeQtde smallint, ")
                .AppendLine("  @DiaPrioridade datetime ")
                .AppendLine("set @DiaPrioridade = convert(datetime, @Dia, 103) ")
                .AppendLine("create table #Caracteristica( ")
                .AppendLine("  CId numeric primary Key) ")
                .AppendLine("declare @Cont integer declare @Aux integer ")
                .AppendLine("set @Cont = 1 ")
                .AppendLine("while Len(@ListaCaract) > @Cont begin ")
                .AppendLine("  set @Aux = (select charindex('.', @ListaCaract, @Cont)) ")
                .AppendLine("  insert #Caracteristica(CId) ")
                .AppendLine("    values(substring(@ListaCaract, @Cont, @Aux - @Cont)) ")
                .AppendLine("  set @Cont = @Aux + 1 ")
                .AppendLine("end ")
                .AppendLine("select @Qtde = count(distinct CarGrupo) from ")
                .AppendLine("  #Caracteristica cc inner join TbCaracteristica c with (nolock) ")
                .AppendLine("  on cc.CId = c.CarId ")
                .AppendLine("create table #Apto( ")
                .AppendLine("  AptoId numeric Identity (1,1), ")
                .AppendLine("  ApaId smallint, ")
                .AppendLine("  ApaDesc varchar(10), ")
                .AppendLine("  ApaOcupado char(1), ")
                .AppendLine("  ApaHoras smallint, ")
                .AppendLine("  ApaCamaCasal smallint, ")
                .AppendLine("  ApaCamaSolteiro smallint, ")
                .AppendLine("  ApaCamaEspecial smallint, ")
                .AppendLine("  ApaCamaExtra smallint, ")
                .AppendLine("  ApaBercoEspecial smallint, ")
                .AppendLine("  ApaBerco smallint, ")
                .AppendLine("  ApaFronha smallint, ")
                .AppendLine("  ApaJogoToalha smallint, ")
                .AppendLine("  ApaConferencia char(1) default('N')) ")
                .AppendLine("create index ISAptoId on #Apto ( AptoId ASC ) ")
                .AppendLine("set @AptoPrioridadeQtde = 0 ")
                .AppendLine("declare Apto_cursor cursor for ")
                .AppendLine("  select a.ApaId, a.ApaDesc, a.ApaStatus from TbApartamento a with (nolock) ")
                .AppendLine("    where a.ApaDesc like '%' + ")
                .AppendLine("      case ")
                .AppendLine("        when @ApaId <> '0' then @ApaId ")
                .AppendLine("        else a.ApaDesc ")
                .AppendLine("      end + '%' ")
                .AppendLine("    and a.ApaFederacao = ")
                .AppendLine("      case ")
                .AppendLine("        when @Federacao = 'T' then a.ApaFederacao ")
                .AppendLine("        else @Federacao ")
                .AppendLine("      end ")
                .AppendLine("    and (case ")
                .AppendLine("      when @Qtde > 0 then ")
                .AppendLine("        (select count(1) from VwCaracteristicaAcmApa c with (nolock) where c.CarId in ")
                .AppendLine("          (select CId from #Caracteristica) ")
                .AppendLine("          and a.ApaId = c.ApaId) ")
                .AppendLine("      else 0 end) = @Qtde ")
                .AppendLine("    union ")
                .AppendLine("  select a.ApaId, a.ApaDesc, 'M' as ApaStatus from TbApartamento a with (nolock) ")
                .AppendLine("    where a.ApaDesc like '%' + ")
                .AppendLine("      case ")
                .AppendLine("        when @ApaId <> '0' then @ApaId ")
                .AppendLine("        else a.ApaDesc ")
                .AppendLine("      end + '%' ")
                .AppendLine("    and a.ApaFederacao = ")
                .AppendLine("      case ")
                .AppendLine("        when @Federacao = 'T' then a.ApaFederacao ")
                .AppendLine("        else @Federacao ")
                .AppendLine("      end ")
                .AppendLine("    and a.ApaStatus = 'O' ")
                .AppendLine("    and exists (select 1 from TbManutencao m with (nolock) where m.ApaId = a.ApaId and m.ManDataConclusao is null) ")
                .AppendLine("    and (case ")
                .AppendLine("      when @Qtde > 0 then ")
                .AppendLine("        (select count(1) from VwCaracteristicaAcmApa c with (nolock) where c.CarId in ")
                .AppendLine("          (select CId from #Caracteristica) ")
                .AppendLine("          and a.ApaId = c.ApaId) ")
                .AppendLine("      else 0 end) = @Qtde ")
                .AppendLine("    order by a.ApaId ")
                .AppendLine("open Apto_cursor ")
                .AppendLine("close Apto_cursor ")
                .AppendLine("deallocate Apto_cursor ")
                .AppendLine("create table #Prioridade( ")
                .AppendLine("  ApaId smallint, ")
                .AppendLine("  DataIni datetime, ")
                .AppendLine("  ApaStatus char(1)) ")
                .AppendLine("declare @LimiteIdadeBerco integer ")
                .AppendLine("select @LimiteIdadeBerco = LimiteIdadeBerco from TbParametro with (nolock) ")
                .AppendLine("declare Prioridade_cursor cursor for ")
                .AppendLine("  select h.SolId, h.ApaId, min(h.HosDataIniSol) as HosDataIniSol, ")
                .AppendLine("    count(h.HosId) as Integrante, ")
                .AppendLine("      sum(case when DbFuncao.Dbo.FuIdade(IntDtNascimento, IntDataIni) < @LimiteIdadeBerco then 1 else 0 end) SolBerco ")
                .AppendLine("    from TbHospedagem h with (nolock) inner join TbSolicitacao s with (nolock) on h.SolId = s.SolId ")
                .AppendLine("    inner join TbIntegrante i with (nolock) on i.IntId = h.IntId ")
                .AppendLine("    inner join TbAcomodacao a with (nolock) on a.AcmId = s.AcmId ")
                .AppendLine("    where (((convert(datetime, convert(char(11), @DiaPrioridade)) between ")
                .AppendLine("          convert(datetime, convert(char(11), h.HosDataIniSol)) and ")
                .AppendLine("          convert(datetime, convert(char(11), h.HosDataFimSol)))) ")
                .AppendLine(")          and convert(datetime,CONVERT(char(11), h.HosDataFimSol)) > CONVERT(datetime, CONVERT(CHAR(11), getdate())) ")
                '.AppendLine(") and h.HosDataFimSol > getdate() ")
                .AppendLine("	and h.HosDataFimReal is null ")
                .AppendLine("    group by h.SolId, h.ApaId, a.AcmDescricao ")
                .AppendLine("    order by a.AcmDescricao ")
                .AppendLine("open Prioridade_cursor ")
                .AppendLine("fetch next from Prioridade_cursor ")
                .AppendLine("  into @SolId, @ApaId, @DataIni, @Integrante, @SolBerco ")
                .AppendLine("while @@fetch_status = 0 ")
                .AppendLine("begin ")
                .AppendLine("  if @ApaId is null ")
                .AppendLine("  begin ")
                .AppendLine("    if (@ApaId is null) ")
                .AppendLine("      select top 1 @ApaId = a.ApaId, @ApaDesc = a.ApaDesc, @ApaStatus = a.Ordem, @CC = a.AcmCC, @CS = a.AcmCS, ")
                .AppendLine("        @CE = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante - a.AcmCC * 2 - a.AcmCS ")
                .AppendLine("            else 0 ")
                .AppendLine("          end, ")
                .AppendLine("        @BE = @SolBerco, ")
                .AppendLine("        @JT = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @FR = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @ApaCamaExtra = ApaCamaExtra, @ApaBerco = ApaBerco ")
                .AppendLine("        from VwDisponibilidadeAtualSemLock d with (nolock) inner join VwListaOrdemPrioridade a with (nolock) ")
                .AppendLine("        on d.ApaId = a.ApaId ")
                .AppendLine("        and d.SolId = @SolId ")
                .AppendLine("        and d.Status = 'D' ")
                .AppendLine("        and a.Ordem = '1' ")
                .AppendLine("        where not exists (select 1 from #Prioridade p where p.ApaId = d.ApaId) ")
                .AppendLine("        order by a.Ordem, a.ApaBerco desc, a.Integrante desc ")
                .AppendLine("    if (@ApaId is null) ")
                .AppendLine("      select top 1 @ApaId = a.ApaId, @ApaDesc = a.ApaDesc, @ApaStatus = a.Ordem, @CC = a.AcmCC, @CS = a.AcmCS, ")
                .AppendLine("        @CE = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante - a.AcmCC * 2 - a.AcmCS ")
                .AppendLine("            else 0 ")
                .AppendLine("          end, ")
                .AppendLine("        @BE = @SolBerco, ")
                .AppendLine("        @JT = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @FR = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @ApaCamaExtra = ApaCamaExtra, @ApaBerco = ApaBerco ")
                .AppendLine("        from VwDisponibilidadeAtualSemLock d with (nolock) inner join VwListaOrdemPrioridade a with (nolock) ")
                .AppendLine("        on d.ApaId = a.ApaId ")
                .AppendLine("        and d.SolId = @SolId ")
                .AppendLine("        and d.Status = 'D' ")
                .AppendLine("        and a.Ordem = '2' ")
                .AppendLine("        where not exists (select 1 from #Prioridade p where p.ApaId = d.ApaId) ")
                .AppendLine("        order by a.Ordem, a.ApaBerco desc, a.Integrante desc ")
                .AppendLine("    if (@ApaId is null) ")
                .AppendLine("      select top 1 @ApaId = a.ApaId, @ApaDesc = a.ApaDesc, @ApaStatus = a.Ordem, @CC = a.AcmCC, @CS = a.AcmCS, ")
                .AppendLine("        @CE = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante - a.AcmCC * 2 - a.AcmCS ")
                .AppendLine("            else 0 ")
                .AppendLine("          end, ")
                .AppendLine("        @BE = @SolBerco, ")
                .AppendLine("        @JT = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @FR = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @ApaCamaExtra = ApaCamaExtra, @ApaBerco = ApaBerco ")
                .AppendLine("        from VwDisponibilidadeAtualSemLock d with (nolock) inner join VwListaOrdemPrioridade a with (nolock) ")
                .AppendLine("        on d.ApaId = a.ApaId ")
                .AppendLine("        and d.SolId = @SolId ")
                .AppendLine("        and d.Status = 'D' ")
                .AppendLine("        and a.Ordem = '3' ")
                .AppendLine("        where not exists (select 1 from #Prioridade p where p.ApaId = d.ApaId) ")
                .AppendLine("        order by a.Ordem, a.ApaBerco desc, a.Integrante desc ")
                .AppendLine("    if (@ApaId is null) ")
                .AppendLine("      select top 1 @ApaId = a.ApaId, @ApaDesc = a.ApaDesc, @ApaStatus = a.Ordem, @CC = a.AcmCC, @CS = a.AcmCS, ")
                .AppendLine("        @CE = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante - a.AcmCC * 2 - a.AcmCS ")
                .AppendLine("            else 0 ")
                .AppendLine("          end, ")
                .AppendLine("        @BE = @SolBerco, ")
                .AppendLine("        @JT = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @FR = ")
                .AppendLine("          case ")
                .AppendLine("            when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("            else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("          end, ")
                .AppendLine("        @ApaCamaExtra = ApaCamaExtra, @ApaBerco = ApaBerco ")
                .AppendLine("        from VwDisponibilidadeAtualSemLock d with (nolock) inner join VwListaOrdemPrioridade a with (nolock) ")
                .AppendLine("        on d.ApaId = a.ApaId ")
                .AppendLine("        where d.SolId = @SolId ")
                .AppendLine("        and d.Status = 'D' ")
                .AppendLine("        and a.Ordem = '4' ")
                .AppendLine("        and not exists (select 1 from #Prioridade p where p.ApaId = d.ApaId) ")
                .AppendLine("        order by a.Ordem, a.ApaBerco desc, a.Integrante desc ")
                .AppendLine("  end ")
                .AppendLine("  begin ")
                .AppendLine("    select top 1 @ApaDesc = ApaDesc, @ApaStatus = ")
                .AppendLine("      case ")
                .AppendLine("        when ApaStatus = 'L' then '1' ")
                .AppendLine("        when ApaStatus = 'A' then '2' ")
                .AppendLine("        when ApaStatus = 'O' then '3' ")
                .AppendLine("        else '4' ")
                .AppendLine("     end from TbApartamento with (nolock) where ApaId = @ApaId ")
                .AppendLine("    select top 1 @ApaStatus = a.Ordem, @CC = a.AcmCC, @CS = a.AcmCS, ")
                .AppendLine("      @CE = ")
                .AppendLine("        case ")
                .AppendLine("          when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante - a.AcmCC * 2 - a.AcmCS ")
                .AppendLine("          else 0 ")
                .AppendLine("        end, ")
                .AppendLine("      @BE = @SolBerco, ")
                .AppendLine("      @JT = ")
                .AppendLine("        case ")
                .AppendLine("          when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("          else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("        end, ")
                .AppendLine("      @FR = ")
                .AppendLine("        case ")
                .AppendLine("          when @Integrante > a.AcmCC * 2 + a.AcmCS then @Integrante + @SolBerco ")
                .AppendLine("          else a.AcmCC * 2 + a.AcmCS + @SolBerco ")
                .AppendLine("        end, ")
                .AppendLine("      @ApaCamaExtra = ApaCamaExtra, @ApaBerco = ApaBerco ")
                .AppendLine("      from VwDisponibilidadeAtualSemLock d with (nolock) inner join VwListaOrdemPrioridade a with (nolock) ")
                .AppendLine("      on d.ApaId = a.ApaId ")
                .AppendLine("      and d.SolId = @SolId ")
                .AppendLine("      and d.ApaId = @ApaId ")
                .AppendLine("      and d.Status = 'A' ")
                .AppendLine("      order by a.Ordem ")
                .AppendLine("  end ")
                .AppendLine("  if not exists (select 1 from TbHospedagem with (nolock) where SolId = @SolId and HosDataIniReal is not null) ")
                .AppendLine("    insert #Prioridade ")
                .AppendLine("      values(@ApaId, @DataIni, @ApaStatus) ")
                .AppendLine("  begin ")
                .AppendLine("    if @ApaStatus in ('1','3') ")
                .AppendLine("    begin ")
                .AppendLine("      if (@ApaCamaExtra <> @CE) ")
                .AppendLine("      begin ")
                .AppendLine("        if @ApaCamaExtra > @CE ")
                .AppendLine("          set @CE = @CE - @ApaCamaExtra ")
                .AppendLine("        else ")
                .AppendLine("          set @CE = abs(@CE - @ApaCamaExtra) ")
                .AppendLine("      end ")
                .AppendLine("      else ")
                .AppendLine("      begin ")
                .AppendLine("        set @ApaCamaExtra = 0 ")
                .AppendLine("        set @CE = 0 ")
                .AppendLine("      end ")
                .AppendLine("      if (@ApaBerco <> @BE) ")
                .AppendLine("      begin ")
                .AppendLine("        if @ApaBerco > @BE ")
                .AppendLine("          set @BE = @BE - @ApaBerco ")
                .AppendLine("        else ")
                .AppendLine("          set @BE = abs(@BE - @ApaBerco) ")
                .AppendLine("      end ")
                .AppendLine("      else ")
                .AppendLine("      begin ")
                .AppendLine("        set @ApaBerco = 0 ")
                .AppendLine("        set @BE = 0 ")
                .AppendLine("      end ")
                .AppendLine("      set @FR = 0 ")
                .AppendLine("      set @JT = 0 ")
                .AppendLine("      set @CC = 0 ")
                .AppendLine("      set @CS = 0 ")
                .AppendLine("    end ")
                .AppendLine("    else ")
                .AppendLine("    begin ")
                .AppendLine("      if (@ApaCamaExtra <> @CE) ")
                .AppendLine("      begin ")
                .AppendLine("        if @ApaCamaExtra > @CE ")
                .AppendLine("          set @CE = @CE - @ApaCamaExtra ")
                .AppendLine("        else ")
                .AppendLine("          set @CE = abs(@CE - @ApaCamaExtra) ")
                .AppendLine("      end ")
                .AppendLine("      else ")
                .AppendLine("      begin ")
                .AppendLine("        set @ApaCamaExtra = 0 ")
                .AppendLine("        set @CE = 0 ")
                .AppendLine("      end ")
                .AppendLine("      if (@ApaBerco <> @BE) ")
                .AppendLine("      begin ")
                .AppendLine("        if @ApaBerco > @BE ")
                .AppendLine("          set @BE = @BE - @ApaBerco ")
                .AppendLine("        else ")
                .AppendLine("          set @BE = abs(@BE - @ApaBerco) ")
                .AppendLine("      end ")
                .AppendLine("      else ")
                .AppendLine("      begin ")
                .AppendLine("        set @ApaBerco = 0 ")
                .AppendLine("        set @BE = 0 ")
                .AppendLine("      end ")
                .AppendLine("    end ")
                .AppendLine("    set @CE = 0 ")
                .AppendLine("    set @BE = 0 ")
                .AppendLine("    set @ApaCamaExtra = 0 ")
                .AppendLine("    set @ApaBerco = 0 ")
                .AppendLine("    if (@ApaId is not null) and (((@CC > 0) or (@CS > 0) or (@CE > 0) or (@BE > 0) or (@FR > 0) or (@JT > 0) or (@ApaCamaExtra > 0) or (@ApaBerco > 0)) ")
                .AppendLine("      or ((@ApaStatus = '3') and not exists (select 1 from TbHospedagem with (nolock) where SolId = @SolId and HosDataIniReal is not null))) ")
                .AppendLine("    begin ")
                .AppendLine("      if (@ApaStatus = '3') and not exists (select 1 from TbHospedagem with (nolock) where SolId = @SolId and HosDataIniReal is not null) ")
                .AppendLine("        set @ApaStatus = '6' ")
                .AppendLine("      set @AptoPrioridadeQtde = @AptoPrioridadeQtde + 1 ")
                .AppendLine("      if not exists (select 1 from #Apto where ")
                .AppendLine("        (ApaId is null)) ")
                .AppendLine("        insert #Apto (ApaId, ApaDesc, ApaHoras, ApaCamaCasal, ApaCamaSolteiro, ApaCamaEspecial, ")
                .AppendLine("                             ApaBercoEspecial, ApaFronha, ApaJogoToalha, ApaOcupado, ApaCamaExtra, ApaBerco) ")
                .AppendLine("          values (@ApaId, @ApaDesc, datepart(hh, @DataIni), @CC, @CS, @CE, @BE, @FR, @JT, ")
                .AppendLine("            case ")
                .AppendLine("              when @ApaStatus = '3' then 'S' ")
                .AppendLine("              when @ApaStatus = '6' then 'C' ")
                .AppendLine("              else 'N' ")
                .AppendLine("            end, @ApaCamaExtra, @ApaBerco) ")
                .AppendLine("      else ")
                .AppendLine("      begin ")
                .AppendLine("       if @@RowCount = 0 ")
                .AppendLine("        begin ")
                .AppendLine("              if @@RowCount = 0 ")
                .AppendLine("              update #Apto set ")
                .AppendLine("                AptoPrioridade1 = @ApaId, ")
                .AppendLine("                AptoPrioridadeDesc1 = @ApaDesc, ")
                .AppendLine("                AptoPrioridadeHr1 = datepart(hh, @DataIni), ")
                .AppendLine("                AptoPrioridadeCC1 = @CC, ")
                .AppendLine("                AptoPrioridadeCS1 = @CS, ")
                .AppendLine("                AptoPrioridadeCE1 = @CE, ")
                .AppendLine("                ApaCamaExtra1 = @ApaCamaExtra, ")
                .AppendLine("                AptoPrioridadeBE1 = @BE, ")
                .AppendLine("                ApaBerco1 = @ApaBerco, ")
                .AppendLine("                AptoPrioridadeFR1 = @FR, ")
                .AppendLine("                AptoPrioridadeJT1 = @JT, ")
                .AppendLine("                AptoPrioridadeOcupado1 = ")
                .AppendLine("                  case ")
                .AppendLine("                    when @ApaStatus = '3' then 'S' ")
                .AppendLine("                    when @ApaStatus = '6' then 'C' ")
                .AppendLine("                    else 'N' ")
                .AppendLine("                  end ")
                .AppendLine("                where AptoId = (select min(AptoId) from #Apto where AptoPrioridade1 is null) ")
                .AppendLine("          end ")
                .AppendLine("       end ")
                .AppendLine("    end ")
                .AppendLine("  end ")
                .AppendLine("  fetch next from Prioridade_cursor ")
                .AppendLine("    into @SolId, @ApaId, @DataIni, @Integrante, @SolBerco ")
                .AppendLine("end ")
                .AppendLine("close Prioridade_cursor ")
                .AppendLine("deallocate Prioridade_cursor ")
                .AppendLine("select *, ")
                .AppendLine("  case ")
                .AppendLine("    when @AptoPrioridadeQtde > 0 then @AptoPrioridadeQtde ")
                .AppendLine("    else null ")
                .AppendLine("  end as AptoPrioridadeQtde from #Apto ")
                If AliasBanco = "TurismoSocialPiri" Then
                    .AppendLine("order by APADESC ASC ")
                Else
                    .AppendLine("order by APAID ASC ")
                End If
                .AppendLine("drop table #Prioridade ")
                .AppendLine("drop table #Apto ")
                .AppendLine("drop table #Caracteristica ")
                Return PreencheLista(Conn.consulta(VarSql.ToString))
            End With
        Catch ex As Exception
            Throw New Exception(ex.StackTrace.ToString.Replace(Chr(13), ""))
        End Try
    End Function
    Private Function PreencheLista(ByVal ResultadoConsulta As System.Data.SqlClient.SqlDataReader) As IList
        Dim Lista As IList
        Lista = New ArrayList
        If ResultadoConsulta.HasRows Then
            While ResultadoConsulta.Read
                ObjPrioridadeVO = New PrioridadeVO
                With ObjPrioridadeVO
                    .ApaBerco = ResultadoConsulta.Item("ApaBerco")
                    .ApaBercoEspecial = ResultadoConsulta.Item("ApaBercoEspecial")
                    .ApaCamaCasal = ResultadoConsulta.Item("ApaCamaCasal")
                    .ApaCamaEspecial = ResultadoConsulta.Item("ApaCamaEspecial")
                    .ApaCamaExtra = ResultadoConsulta.Item("ApaCamaExtra")
                    .ApaCamaSolteiro = ResultadoConsulta.Item("ApaCamaSolteiro")
                    .ApaConferencia = ResultadoConsulta.Item("ApaConferencia")
                    .ApaDesc = ResultadoConsulta.Item("ApaDesc")
                    .ApaFronha = ResultadoConsulta.Item("ApaFronha")
                    .ApaHoras = ResultadoConsulta.Item("ApaHoras")
                    .ApaId = ResultadoConsulta.Item("ApaId")
                    .ApaJogoToalha = ResultadoConsulta.Item("ApaJogoToalha")
                    .ApaOcupado = ResultadoConsulta.Item("ApaOcupado")
                    .AptoPrioridadeQtde = ResultadoConsulta.Item("AptoPrioridadeQtde")
                End With
                Lista.Add(ObjPrioridadeVO)
            End While
        End If
        ResultadoConsulta.Close()
        Return Lista
    End Function
End Class
