Imports Microsoft.VisualBasic

Public Class ModelosBoletos
    Public Function ModeloEmissivo(Vencimento As String) As String
        Dim BoletoEmissivo As String = ""
        BoletoEmissivo += "<!DOCTYPE HTML PUBLIC " & "-//W3C//DTD HTML 4.0 Transitional//EN" & "> "

        '            <%
        '            Dim Banco, CodBanco, Cedente, Reserva, Vencimento, Sacado, AgeCodCed
        '            Dim NossoNum, Demonstrativo, VlrDoc, CodigoPgto, DataDocumento, DataProces, Codigoipte
        '            Dim CodigoBarra, Periodo, Entrada, Saida, Comando, QdtePess, End1
        '            Dim Boleto, Acomodacao, Destino, Hospedagem, UFDestino, NomeResp, EnderecoResp
        '            Dim BairroResp, CidadeResp, EstadoResp, Emissivo

        '            Banco = Request("Banco"
        '            CodBanco = Request("CodBanco"
        '            Cedente = Request("Cedente"
        '            Reserva = Request("Reserva"
        '            Vencimento = Request("Vencimento"
        '            Sacado = Request("Sacado"
        '            AgeCodCed = Request("AgeCodCed"
        '            NossoNum = Request("NossoNum"
        '            Demonstrativo = Request("Demonstrativo"
        '            VlrDoc = Request("VlrDoc"
        '            DataDocumento = Request("DataDocumento"
        '            DataProces = Request("DataProces"
        '            Codigoipte = Request("Codigoipte"
        '            CodigoBarra = Request("CodigoBarra"
        '            End1 = Request("End1"
        '            Periodo = Request("Periodo"
        '            Entrada = Request("Entrada"
        '            Saida = Request("Saida"
        '            Comando = Request("Comando"
        '            QdtePess = Request("QdtePess"
        '            Boleto = Request("Boleto"
        '            Acomodacao = Request("Acomodacao"
        '            Destino = Request("Destino"
        '            Hospedagem = Request("Hospedagem"
        '            UFDestino = Request("UFDestino"
        '            NomeResp = Request("NomeResp"
        '            EnderecoResp = Request("EnderecoResp"
        '            BairroResp = Request("BairroResp"
        '            CidadeResp = Request("CidadeResp"
        '            EstadoResp = Request("EstadoResp"
        '            Emissivo = Request("Emissivo"
        '%>

        BoletoEmissivo += "<html> "
        BoletoEmissivo += "<head> "
        BoletoEmissivo += "<title>Cobrança</title> "
        BoletoEmissivo += "    <meta http-equiv=" & "Content-Type" & "content=" & "text/html; charset=ISO-8859-1" & "> "
        BoletoEmissivo += "    <meta content=" & "Microsoft FrontPage 4.0" & "name=" & "GENERATOR" & "> "
        BoletoEmissivo += "</head> "
        BoletoEmissivo += "<form name=" & "Boleto" & " action=""> "
        BoletoEmissivo += "<body onload=" & "printPage()" & "> "
        BoletoEmissivo += "    <table cellspacing=" & "0" & "cellpadding=" & "0" & "width=" & "640" & "border=" & "0" & "height=" & "53""&> "
        BoletoEmissivo += "        <tbody> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td width=" & "86" & "rowspan=" & "2" & "height=" & "23" & "> "
        BoletoEmissivo += "                    <p align=" & "center" & "> "
        BoletoEmissivo += "                        <img border=" & "0" & "src=" & "../aspx_styles/Images/GIF%20SESC.gif" & "> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "                <td width=" & "411" & "height=" & "29" & "> "
        BoletoEmissivo += "                    SERVIÇO SOCIAL DO COMÉRCIO "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "                <td valign=" & "bottom" & "align=" & "right" & "width=" & "143" & "rowspan=" & "2" & "height=" & "23" & "> "
        BoletoEmissivo += "                    <p align=" & "center" & "> "
        BoletoEmissivo += "            Via Sacado "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td width=" & "411" & "height=" & "1" & "> "
        BoletoEmissivo += "                    Departamento Regional em Goiás "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "        </tbody> "
        BoletoEmissivo += "    </table> "
        BoletoEmissivo += "    <table cellspacing=" & "0" & "cellpadding=" & "2" & "width=" & "640" & "border=" & "1" & "height=" & "1" & "> "
        BoletoEmissivo += "        <tbody> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "612" & "height=" & "18" & "colspan=" & "3" & "> "
        BoletoEmissivo += "                    <sup><font face=" & "Arial" & "size=" & "2" & ">&nbsp;</font></sup><font face=" & "Arial" & "><sup>Cedente</sup></font><font "
        BoletoEmissivo += "                        face=" & "arial" & "size=" & "2" & ">&nbsp;&nbsp; SESC Central de Reservas</font> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "70" & "height=" & "18" & "> "
        BoletoEmissivo += "                    <sup><font face=" & "Arial" & "size=" & "2" & ">&nbsp;</font></sup><font face=" & "Arial" & "><sup>Vencimento</sup></font><font "
        BoletoEmissivo += "                        face=" & "arial" & "size=" & "2" & ">&nbsp;&nbsp;<%response.write Vencimento%></font> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "130" & "height=" & "9" & "> "
        BoletoEmissivo += "                    &nbsp;<sup>Data</sup>&nbsp;&nbsp;&nbsp;" & Vencimento & "> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "272" & "height=" & "9" & "> "
        BoletoEmissivo += "                    <sup>&nbsp;Nº de Controle</sup>&nbsp;&nbsp;&nbsp;<%response.write NossoNum%> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "149" & "height=" & "9" & "> "
        BoletoEmissivo += "                    <sup>&nbsp;Nº de Pessoas</sup>&nbsp;&nbsp;&nbsp;<%response.write QdtePess%> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "198" & "height=" & "9" & "> "
        BoletoEmissivo += "                    <sup>&nbsp;Valor</sup>&nbsp;&nbsp;&nbsp;R$ "
        BoletoEmissivo += "                    <%response.write VlrDoc%> "
        BoletoEmissivo += "                    &nbsp; "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "464" & "height=" & "1" & "colspan=" & "3" & "> "
        BoletoEmissivo += "                    &nbsp;Período &nbsp; "
        BoletoEmissivo += "                    <%response.write NomeReserva%> "
        BoletoEmissivo += "                    <br> "
        BoletoEmissivo += "                    &nbsp;Sacado&nbsp;&nbsp;<%response.write Sacado%> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "        </tbody> "
        BoletoEmissivo += "    </table> "
        BoletoEmissivo += "    <table cellspacing=" & "0" & "cellpadding=" & "2" & "width=" & "640" & "border=" & "1" & "height=" & "295" & "> "
        BoletoEmissivo += "        <tbody> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "100%" & "height=" & "88" & "colspan=" & "2" & "> "
        BoletoEmissivo += "                    <font face=" & "Arial" & "size=" & "2" & ">Demonstrativo Turismo Social - Excursão/Passeio Nº: "
        BoletoEmissivo += "                        <%response.write Reserva%>&nbsp;/&nbsp;<%response.write QdtePess%> "
        BoletoEmissivo += "                        Integrante(s) <font face=" & "arial" & "size=" & "2" & "> "
        BoletoEmissivo += "                            <br> "
        BoletoEmissivo += "Período: "
        BoletoEmissivo += "                            <%response.write Periodo%> "
        BoletoEmissivo += "                            <br> "
        BoletoEmissivo += "                            <br> "
        BoletoEmissivo += "Destino: "
        BoletoEmissivo += "                            <%response.write Destino%>&nbsp;-&nbsp;<%response.write UFDestino%> "
        BoletoEmissivo += "                            <br> "
        BoletoEmissivo += "Hospedagem: "
        BoletoEmissivo += "                            <%response.write Hospedagem%></font> "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        <p> "
        BoletoEmissivo += "                            <font face=" & "arial" & "size=" & "2" & ">Saída: SESC Universitário / 06h00 "
        BoletoEmissivo += "                                <br> "
        BoletoEmissivo += "                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Av. Universitária, 1749 - "
        BoletoEmissivo += "                                St Universitário</font> "
        BoletoEmissivo += "                        </p> "
        BoletoEmissivo += "                    </font> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "100%" & "height=" & "56" & "colspan=" & "2" & "> "
        BoletoEmissivo += "                    <font face=" & "arial" & "size=" & "2" & "> "
        BoletoEmissivo += "                        <center> "
        BoletoEmissivo += "                            <b>ATENÇÃO (*) Valores e serviços sujeitos a alteração.</b></center> "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        A Excursão/Passeio será <b>cancelado automaticamente </b>caso não ocorra o pagamento "
        BoletoEmissivo += "                        até o vencimento. "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        A Excursão/Passeio é intransferível. "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        Na ausência do cliente no momento do embarque, não haverá reembolso. "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        O cancelamento da Excursão/Passeio, encaminhado por escrito à Central de Reservas, "
        BoletoEmissivo += "                        obedecerá o seguinte critério de reembolso: </font> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "50%" & "height=" & "56" & "> "
        BoletoEmissivo += "                    <font face=" & "arial" & "size=" & "1" & "> "
        BoletoEmissivo += "                        <center> "
        BoletoEmissivo += "                            CANCELAMENTO EFETUADO:</center> "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        Até 10 dias antes do início "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        do 9º ao 6º dia antes do início "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        do 5º ao 2º dia antes do início "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        a partir do dia anterior ao início</font> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "50%" & "height=" & "56" & "> "
        BoletoEmissivo += "                    <font face=" & "arial" & "size=" & "1" & "> "
        BoletoEmissivo += "                        <center> "
        BoletoEmissivo += "                            PORCENTAGEM DE REEMBOLSO</center> "
        BoletoEmissivo += "                        <br> "
        BoletoEmissivo += "                        <center> "
        BoletoEmissivo += "                            80 % "
        BoletoEmissivo += "                            <br> "
        BoletoEmissivo += "                            70 % "
        BoletoEmissivo += "                            <br> "
        BoletoEmissivo += "                            60 % "
        BoletoEmissivo += "                            <br> "
        BoletoEmissivo += "                            sem reembolso</center> "
        BoletoEmissivo += "                    </font> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "center" & "width=" & "100%" & "height=" & "6" & "colspan=" & "2" & "> "
        BoletoEmissivo += "                    <p align=" & "center" & "> "
        BoletoEmissivo += "                        <sup>Contato Central de Reservas: reservas.caldasnovas@sescgo.com.br </sup> "
        BoletoEmissivo += "</td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "        </tbody> "
        BoletoEmissivo += "    </table> "
        BoletoEmissivo += "    <table cellspacing=" & "0" & "cellpadding=" & "2" & "width=" & "640" & "border=" & "0" & "> "
        BoletoEmissivo += "        <tbody> "
        BoletoEmissivo += "            <tr> "
        BoletoEmissivo += "                <td align=" & "left" & "width=" & "100%" & "> "
        BoletoEmissivo += "                    <p> "
        BoletoEmissivo += "                        <font size=" & "1" & "><sup>&nbsp;2ª Via - Sacado&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "
        BoletoEmissivo += "                            Autenticação Mecânica</sup></font> "
        BoletoEmissivo += "                    <p align=" & "right" & "> "
        BoletoEmissivo += "                        <font size=" & "1" & ">Cortar aqui...</font> "
        BoletoEmissivo += "                    </p> "
        BoletoEmissivo += "                </td> "
        BoletoEmissivo += "            </tr> "
        BoletoEmissivo += "        </tbody> "
        BoletoEmissivo += "    </table> "
        BoletoEmissivo += "</body> "
        BoletoEmissivo += "</form> "
        BoletoEmissivo += "</html> "
        Return BoletoEmissivo
    End Function
End Class
