Imports System
Imports System.Collections
Imports System.Text
Imports Microsoft.VisualBasic
Public Class RestaurantePrevisoesDAO
    Dim ObjRestaurantePrevisoesVO As RestaurantePrevisoesVO
    Dim ObjRestaurantePrevisoesDAO As RestaurantePrevisoesDAO

    Public Function Consultar(ByVal AliasBanco As String, ByVal Dia As String, ByVal Tipo As String) As IList
        Try
            Dim Conn = New Banco.Conexao(AliasBanco)
            Dim VarSql = New StringBuilder("SET NOCOUNT ON ")
            Dim Contador = 0
            With VarSql
                'Criando tabela para inserção de todas a consultas - Desjejum,Almoço e Jantar'
                .AppendLine("Create Table #Completa( ")
                .AppendLine("RefeicaoTipo char(1), ")
                .AppendLine("DesjejumRefeicao int, ")
                .AppendLine("Estada int, ")
                .AppendLine("DesjejumRefeicaoConfirmado int ")
                .AppendLine(") ")
                .AppendLine("Declare @Dia datetime, @Tipo char(1) ")
                .AppendLine("Set @Dia=' " & Dia & "' ")

                'Tabela Auxiliar para inserção
                .AppendLine("create table #Aux( ")
                .AppendLine("ResStatus char(1), ")
                .AppendLine("IntStatus char(1), ")
                .AppendLine("IntTipo char(1), ")
                .AppendLine("IntDataIni datetime, ")
                .AppendLine("IntDataFim datetime, ")
                .AppendLine("IntDataIniReal datetime, ")
                .AppendLine("IntDataFimReal datetime, ")
                .AppendLine("IntDesjejum char(1), ")
                .AppendLine("IntAlmoco char(1), ")
                .AppendLine("IntJantar char(1), ")
                .AppendLine("IntPasAntCaf int default (0), ")
                .AppendLine("IntPasAntAlm int default (0), ")
                .AppendLine("IntPasAntJan int default (0)) ")
                .AppendLine("create index ISIntStatus on #Aux ( IntTipo ASC ) ")
                .AppendLine("create index ISIntTipo on #Aux ( IntTipo ASC ) ")
                .AppendLine("create index ISIntDataIni on #Aux ( IntDataIni ASC ) ")
                .AppendLine("create index ISIntDataFim on #Aux ( IntDataFim ASC ) ")
                .AppendLine("create index ISIntDataIniReal on #Aux ( IntDataIniReal ASC ) ")
                .AppendLine("create index ISIntDataFimReal on #Aux ( IntDataFimReal ASC ) ")
                .AppendLine("create index ISIntDesjejum on #Aux ( IntDesjejum ASC ) ")
                .AppendLine("create index ISIntAlmoco on #Aux ( IntAlmoco ASC ) ")
                .AppendLine("create index ISIntJantar on #Aux ( IntJantar ASC ) ")
                'Irá passar por três vezes, sendo Desjejum, Almoço e Jantar
                While Contador <= 2
                    '.AppendLine("insert into #Completa(RefeicaoTipo,DesjejumRefeicao,Estada,DesjejumRefeicaoConfirmado)  ")

                    Select Case Contador
                        Case 0
                            .AppendLine("Set @Tipo= 'D' ")
                        Case 1
                            .AppendLine("Set @Tipo= 'A' ")
                        Case 2
                            .AppendLine("Set @Tipo= 'J' ")
                    End Select

                    'Iniciando a inserção dos dados
                    .AppendLine("insert into #Aux (ResStatus, IntStatus, IntTipo, IntDataIni, IntDataFim, IntDataIniReal, IntDataFimReal, ")
                    .AppendLine("IntDesjejum, IntAlmoco, IntJantar, IntPasAntCaf, IntPasAntAlm, IntPasAntJan) ")

                    .AppendLine("select '', i.IntStatus, 'P' as IntTipo, i.IntDataIni, i.IntDataFim, i.IntDataIniReal, i.IntDataFimReal, ")
                    .AppendLine("i.IntDesjejum, i.IntAlmoco, i.IntJantar, i.IntPasAntCaf, i.IntPasAntAlm, i.IntPasAntJan from  ")
                    .AppendLine("VwPassante i with (nolock) ")
                    .AppendLine("where i.ResId = 0 and i.IntStatus <> 'F' ")
                    .AppendLine("and (IntDataIni >= @Dia and IntDataIni < @Dia + 1) ")
                    .AppendLine("OPTION (OPTIMIZE FOR(@Dia='2012-01-01')) ")

                    .AppendLine("insert into #Aux (ResStatus, IntStatus, IntTipo, IntDataIni, IntDataFim, IntDataIniReal, IntDataFimReal, ")
                    .AppendLine("IntDesjejum, IntAlmoco, IntJantar, IntPasAntCaf, IntPasAntAlm, IntPasAntJan) ")
                    .AppendLine("select r.ResStatus, i.IntStatus, i.IntTipo, i.IntDataIni, i.IntDataFim, i.IntDataIniReal, i.IntDataFimReal, ")
                    .AppendLine("i.IntDesjejum, i.IntAlmoco, i.IntJantar, i.IntPasAntCaf, i.IntPasAntAlm, i.IntPasAntJan from  ")
                    .AppendLine("VwIntegrante i with (nolock) ")
                    .AppendLine("inner join TbReserva r with (nolock) ")
                    .AppendLine("on i.ResId = r.ResId ")
                    .AppendLine("where r.ResStatus in ('E', 'R', 'I', 'P') ")
                    .AppendLine("and ")
                    .AppendLine("(@Dia between ")
                    .AppendLine("dateadd(hh, - datepart(hh, IntDataIni), IntDataIni) ")
                    .AppendLine("and ")
                    .AppendLine("dateadd(hh, - datepart(hh, IntDataFim) - 1, IntDataFim + 1)) ")
                    .AppendLine("and (IntStatus <> 'F') ")
                    .AppendLine("and not exists (select 1 from TbRefeicaoPratoIntegrante pti where pti.IntId = i.IntId) ")
                    .AppendLine("OPTION (OPTIMIZE FOR(@Dia='2012-01-01')) ")
                    'Inserindo o resultado da consulta na tabela #completa que será listada no final
                    .AppendLine("insert into #Completa(RefeicaoTipo,DesjejumRefeicao,Estada,DesjejumRefeicaoConfirmado)  ")

                    'Iniciando a Select de inserção na tabela #Completa
                    .AppendLine("select r.RefeicaoTipo, ")
                    .AppendLine("case ")
                    .AppendLine("when r.RefeicaoTipo = 'D' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where IntDesjejum = 'S' and IntTipo <> '' and ")
                    .AppendLine("((convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) between ")
                    .AppendLine("IntDataIni and IntDataFim and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103) <= IntDataFim) or ")
                    .AppendLine("IntDataIni between ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103) or ")
                    .AppendLine("IntDataFim between ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103))) ")
                    .AppendLine("when r.RefeicaoTipo = 'A' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where IntTipo <> '' and ")
                    .AppendLine("( ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('S','P')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('I','+')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('E','*')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('O','-')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) ")
                    .AppendLine(") ")
                    .AppendLine(") ")
                    .AppendLine("when r.RefeicaoTipo = 'J' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where IntTipo <> '' and ")
                    .AppendLine("( ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('S','P')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('I','+')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('E','*')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('O','-')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) ")
                    .AppendLine(") ")
                    .AppendLine(") ")
                    .AppendLine("end ")
                    .AppendLine("as DesjejumRefeicao, ")

                    'Definindo o valor da Estada
                    .AppendLine("case ")
                    .AppendLine("when r.RefeicaoTipo = 'D' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where IntDesjejum = 'S' and IntStatus = 'E' and IntTipo <> '' and (ResStatus in ('R', 'E')) and ")
                    .AppendLine("((convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) between ")
                    .AppendLine("IntDataIni and IntDataFim and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103) <= IntDataFim) or ")
                    .AppendLine("IntDataIni between ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103) or ")
                    .AppendLine("IntDataFim between ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103))) ")
                    .AppendLine("when r.RefeicaoTipo = 'A' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where (IntStatus = 'E') and (ResStatus in ('R', 'E')) and ")
                    .AppendLine("IntTipo <> '' and ")
                    .AppendLine("( ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('S','P')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('I','+')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('E','*')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('O','-')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) ")
                    .AppendLine(") ")
                    .AppendLine(") ")
                    .AppendLine("when r.RefeicaoTipo = 'J' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where (IntStatus = 'E') and (ResStatus in ('R', 'E')) and ")
                    .AppendLine("IntTipo <> '' and ")
                    .AppendLine("( ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('S','P')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('I','+')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('E','*')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('O','-')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) ")
                    .AppendLine(") ")
                    .AppendLine(") ")
                    .AppendLine("end as Estada, ")

                    'Definindo o valor DesjejumRefeicaoConfirmado
                    .AppendLine("case ")
                    .AppendLine("when r.RefeicaoTipo = 'D' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where IntDesjejum = 'S' and (ResStatus in ('R', 'E')) ")
                    .AppendLine("and IntTipo = 'H' and ")
                    .AppendLine("((convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) between ")
                    .AppendLine("IntDataIni and IntDataFim and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103) <= IntDataFim) or ")
                    .AppendLine("IntDataIni between ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103) or ")
                    .AppendLine("IntDataFim between ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoIni as char(2)) + ':00', 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103) ")
                    .AppendLine("+ ' ' + cast(r.RefeicaoFim as char(2)) + ':00', 103))) ")
                    .AppendLine("when r.RefeicaoTipo = 'A' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where (ResStatus in ('R', 'E')) ")
                    .AppendLine("and IntTipo = 'H' and ")
                    .AppendLine("( ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('S','P')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('I','+')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('E','*')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntAlmoco in ('O','-')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) ")
                    .AppendLine(") ")
                    .AppendLine(") ")
                    .AppendLine("when r.RefeicaoTipo = 'J' then ")
                    .AppendLine("(select count(1) from #Aux ")
                    .AppendLine("where (ResStatus in ('R', 'E')) and ")
                    .AppendLine("IntTipo = 'H' and ")
                    .AppendLine("( ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('S','P')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('I','+')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataIni, 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('E','*')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, -1, IntDataFim), 103), 103)) or ")
                    .AppendLine("( ")
                    .AppendLine("(IntJantar in ('O','-')) and ")
                    .AppendLine("convert(datetime, convert(char(10), @Dia, 103), 103) between ")
                    .AppendLine("convert(datetime, convert(char(10), dateadd(dd, 1, IntDataIni), 103), 103) and ")
                    .AppendLine("convert(datetime, convert(char(10), IntDataFim, 103), 103)) ")
                    .AppendLine(") ")
                    .AppendLine(") ")
                    .AppendLine("end as DesjejumRefeicaoConfirmado ")

                    .AppendLine("from VwRefeicaoRestaurante r with (nolock) ")
                    .AppendLine("where r.RefeicaoTipo = ")
                    .AppendLine("case ")
                    .AppendLine("when @Tipo = 'T' then r.RefeicaoTipo ")
                    .AppendLine("else @Tipo ")
                    .AppendLine("end ")
                    .AppendLine("OPTION (OPTIMIZE FOR(@Dia='2012-01-01')) ")
                    'Zerando os valores da tabela #Aux para iniciar uma nova iserção.
                    .AppendLine("update #Aux set IntDesjejum=0,IntAlmoco=0,IntJantar=0 ")
                    'Incrementando o contador para uma nova passada.
                    Contador = Contador + 1
                End While
                .AppendLine("drop table #Aux ")
                .AppendLine("select * from #Completa ")
                .AppendLine("drop table #Completa ")
            End With
            Return PreencheLista(Conn.consulta(VarSql.ToString))
        Catch ex As Exception
            Throw New Exception(ex.StackTrace.ToString.Replace(Chr(13), ""))
        End Try
    End Function

    Private Function PreencheLista(ByVal ResultadoConsulta As System.Data.SqlClient.SqlDataReader) As IList
        Dim Lista As IList
        Lista = New ArrayList
        If ResultadoConsulta.HasRows Then
            While ResultadoConsulta.Read
                ObjRestaurantePrevisoesVO = New RestaurantePrevisoesVO
                With ObjRestaurantePrevisoesVO
                    .DescricaoRefeicao = ResultadoConsulta.Item("RefeicaoTipo")
                    Select Case ResultadoConsulta.Item("RefeicaoTipo")
                        Case "D"
                            .DescricaoRefeicao = "DESJEJUM"
                        Case "A"
                            .DescricaoRefeicao = "ALMOÇO"
                        Case "J"
                            .DescricaoRefeicao = "JANTAR"
                    End Select

                    .Previsao = ResultadoConsulta.Item("DesjejumRefeicao")
                    .EmEstada = ResultadoConsulta.Item("Estada")
                    .APagar = ResultadoConsulta.Item("DesjejumRefeicao") - ResultadoConsulta.Item("DesjejumRefeicaoConfirmado")
                    .Pago = ResultadoConsulta.Item("DesjejumRefeicaoConfirmado") - .EmEstada
                End With
                Lista.Add(ObjRestaurantePrevisoesVO)
            End While
        End If
        ResultadoConsulta.Close()
        Return Lista
    End Function
End Class
